apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcript-summarizer-api
  namespace: transcript-summarizer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transcript-summarizer-api
  template:
    metadata:
      labels:
        app: transcript-summarizer-api
    spec:
      containers:
      - name: api
        image: ghcr.io/kstv364/transcript-summarizer:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: transcript-summarizer-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 15

---
apiVersion: v1
kind: Service
metadata:
  name: transcript-summarizer-api
  namespace: transcript-summarizer
spec:
  selector:
    app: transcript-summarizer-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transcript-summarizer-ingress
  namespace: transcript-summarizer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: transcript-summarizer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transcript-summarizer-api
            port:
              number: 8000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transcript-summarizer-api-hpa
  namespace: transcript-summarizer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transcript-summarizer-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
