apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  namespace: transcript-summarizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: chromadb/chroma:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: chroma-storage
          mountPath: /chroma/chroma
        env:
        - name: CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER
          value: "chromadb.auth.token.TokenAuthCredentialsProvider"
        - name: CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER
          value: "X-Chroma-Token"
        livenessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/heartbeat
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: chroma-storage
        persistentVolumeClaim:
          claimName: chroma-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: chromadb
  namespace: transcript-summarizer
spec:
  selector:
    app: chromadb
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
  namespace: transcript-summarizer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
