apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: transcript-summarizer
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transcript-summarizer
      component: frontend
  template:
    metadata:
      labels:
        app: transcript-summarizer
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/kstv364/transcript-summarizer-frontend:latest
        ports:
        - containerPort: 7860
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:
        - name: API_BASE_URL
          value: "http://api:8000"
        - name: GRADIO_SERVER_NAME
          value: "0.0.0.0"
        - name: GRADIO_SERVER_PORT
          value: "7860"
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: transcript-summarizer
    component: frontend
spec:
  selector:
    app: transcript-summarizer
    component: frontend
  ports:
  - port: 7860
    targetPort: 7860
    protocol: TCP
  type: ClusterIP
